server:
  port: 7800

spring:
  application:
    name: eureka-server
  security:
    user:
      name: ljj
      password: lijunjie

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://ljj:lijunjie@${eureka.instance.hostname}:${server.port:7800}/eureka/
    register-with-eureka: false
    fetch-registry: false